### ISSUE TITLE
teach me senpai

### ISSUE THREAD

**Issue by bobheadxi** [bibliopals/betterreads-api#1]
docs? 😍 

ps im super down to stick with swift

**Comment by rwblickhan** [comment]
Sorry, what are you looking for exactly? :joy: Vapor's docs are [here](https://docs.vapor.codes/3.0/install/macos/) and Swift docs are [here](https://docs.swift.org/swift-book/GuidedTour/GuidedTour.html)

**Comment by bobheadxi** [comment]
i mean the standard "getting started" stuff in a README

**Comment by rwblickhan** [comment]
Oh uh... working on that 🙂 I'm trying to get docker-compose working for a convenient dev environment - I'll update when that's done (also CI builds obviously)
